### ISSUE TITLE
DFS takes `start` in by move, but BFS and A* take it by reference

### ISSUE THREAD

**Issue by jthemphill** [samueltardieu/pathfinding#118]
The algorithms provided in this crate have *almost* identical APIs, which is really nice. I was able to switch from A* to IDA* to Fringe to DFS with almost no work, which was really neat. (It turned out that I couldn't come up with a heuristic that would make A* better than DFS for my use-case. But the point is it was really easy to try different stuff out thanks to you.)

My only complaint is that DFS inexplicably requires start to be passed in via a move, while the other algorithms don't.

I haven't looked at the other algorithms all that much, but from a cursory glance I think toposort should also take its start parameter in by reference as well.

Anyway, thanks for making this crate, and sorry for raining on your parade by asking for a breaking change =P

**Comment by samueltardieu** [comment]
This peculiarity is documented in the `dfs` help:

> Note that the start node ownership is taken by `dfs` as no clones are made.

Since nodes need to be put in a stack, they must either be owned or implement `Clone`. Since every node can be present only once in the stack, there is no need to clone them, so as not to impose the `Clone` requirement on nodes the start node is taken by value.

Maybe I could offer an alternative function which takes start by reference but makes its parameter type implement `Clone`. I don't know if that would be useful, as if the node can be cloned people can just call `.clone()` on `dfs` first argument as well.

(concerning the topological sort, it has no start node, it is a sorting routine)

**Comment by samueltardieu** [comment]
> But A* and BFS also store their nodes in a data structure, so the same logic should apply. A* and BFS follow the Clone route, while DFS chose the ownership route. I don't much care which you choose - I just think the API would be better if it were consistent.

The difference between DFS and the other algorithms is that:

- DFS only stores every node once, so ownership (which does not require cloning) is preferable;
- other algorithms store nodes in several stacks, so Clone is required and ownership alone would not fulfill this requirement.

I think I can live with such a little disparity between algorithm interfaces, I'm closing it for now.
