### ISSUE TITLE
cargo bench is broken

### ISSUE THREAD

**Issue by lovasoa** [samueltardieu/pathfinding#219]
Hello !
  I am using this crate in my [seam carving implementation](https://crates.io/crates/seamcarving). Trying to improve the performance, I downloaded the sources, and launched `cargo bench`. It errored, saying that a dependency was missing.

The problem seems to come from this commit by @samueltardieu : https://github.com/samueltardieu/pathfinding/commit/31192ab5d0d2d5362b2c00c6bfa4aee543db9d05 .

**Comment by samueltardieu** [comment]
Yes. The criterion dependency (used for benchmarking) was causing `cargo test` to fail because it has a dependency problem which I have had no time to investigate yet (criterion compiles fine by itself when used in a standalone way). Feel free to propose a solution, or wait until I get some free time.

Thanks for the issue, I should have opened it when I committed this.

**Comment by lovasoa** [comment]
Yes, I would be glad to help with this if needed :) `cargo test` worked just fine for me. How can I reproduce the issue you are talking about ?

**Comment by samueltardieu** [comment]
This was probably a transient issue, this is now fixed.

**Comment by lovasoa** [comment]
Thank you @samueltardieu 👍
