### ISSUE TITLE
Adding some method of cancelation to A* computations of unknown length

### ISSUE THREAD

**Issue by trevoranderson** [samueltardieu/pathfinding#285]
Hello!

I was hoping to use the A* implementation in this crate for a project of mine, but I'm running into this problem: if the space I'm searching doesn't have a quick enough solution, the function will eventually eat all available memory and grind the entire computer to a halt. The only workaround I can think of would be spawning a new process to run it and killing the entire process if the computation becomes too costly.

I'd like to add some method to signal to cancel the operation so I can do something like spawn a thread to run this computation, and if I don't receive a result quickly enough I'll signal to drop the calculation and use some fallback strategy instead.

I can always fork and add this functionality myself, but if this is a helpful piece of functionality to have, we can discuss how best to add it to this project (maybe a new version of the function taking a receiver as a parameter?).

**Comment by samueltardieu** [comment]
Hi @trevoranderson.

The computation stops when the `success` function returns `true`. You could either increment a counter in `success` and stop after a given number of iterations, or have it consult an `AtomicBool` and return `true` if this boolean has been set to `true`. Of course in both cases you'll have to check why the computation has stopped (found goal or abortion), but that can be done by comparing the last item in the path with your goal or by using another `AtomicBool` set by `success` when returning prematurely.

As far as I can see, no code change is required in order to do so. Would that work for you?

**Comment by trevoranderson** [comment]
Yeah, that seems reasonable. Thanks Samuel

**Comment by SamCasavant** [comment]
Can I ask that this approach get included in the docs somewhere, or as an example? I don't personally find it intuitive, and I think this is the only place it's explained right now. I don't think it's that uncommon of a problem, the question is also raised by some people in #5 and I think also #253. 

I'd be willing to write it up myself if it's a good idea, although I'm not sure where it should be.

**Comment by Helyos96** [comment]
The "keep up a counter in the success closure" works to an extent. What I really want to do is bail if the current total cost exceeds a threshold, but it would require either:

The `success` closure passes the current total cost:

```
astar(start,
      |p| self.neighbors(p),
      |p| p.distance(goal),
      |cost, p| cost >= 50 || *p == *goal)
```

Or: a new `abort` closure which passes the current total cost and makes the call return `None` if the closure is `true`:

```
astar(start,
      |p| self.neighbors(p),
      |p| p.distance(goal),
      |p| *p == *goal,
      |cost| c >= 50)
```
