### ISSUE TITLE
dfs `start` type is inconsistent with the rest

### ISSUE THREAD

**Issue by tko** [samueltardieu/pathfinding#4]
Not sure if intentional, but all the other algorithms take `&N` as the starting point, only `dfs` takes `N`

**Comment by samueltardieu** [comment]
Yes, this is intentional: contrary to astar/dijkstra/bfs/fringe, elements discovered during a dfs search (such as neighbours returned by the appropriate closure) are stored only in the path, and never in other lists. This allows the use of non-`Clone` types. However, it requires that we take ownership of `start` as to be able to insert it into the resulting `Vec`.

I'll add a note in the documentation, thanks for the remark.
