### ISSUE TITLE
Maximum distance

### ISSUE THREAD

**Issue by beatgammit** [samueltardieu/pathfinding#5]
It would be nice to short-circuit a search if you only want to consider solutions within a certain cost.

I'm mostly interested in the astar implementation (though at least Dijkstra's would also be useful), so passing the current cost and returning an `Option<book>` (where `None` means terminate the search) could work nicely without changing much.

In building a turn based strategy game, but I think this could be useful for other uses of a pathfinding library.

**Comment by samueltardieu** [comment]
What do you mean by `book` here?

**Comment by samueltardieu** [comment]
Closing because no answer was received in a long time.

**Comment by wilg** [comment]
I'd also like to have a maximum cost for pathfinding. I think the `book` above was just their type for one of the generic type parameters. 

I think what you could do is pass the current cost to the `neighbors` function and then you could return zero neighbors if the cost was too high, terminating the search.

**Comment by lunikon** [comment]
I know this is a very old thread, but it's still the "right" one: I face the exact same situation that I want to cut off paths at a certain amount of segments. I could easily keep track of the amount of stops by providing a custom type for the cost, but as @wilg suggested, it would be necessary to get the current cost of a node passed to the successors method. That's kind of a breaking change (since the API of the successor function would change). But would you still consider it?

**Comment by samueltardieu** [comment]
I'm not sure the API of the successor function would have to change. However, a new callback function would probably have to be introduced, such as

```rust
  enum Strategy { Proceed, RejectPath, GiveUp };
  fn strategy(n: &N, cost_so_far: &C, path_length_so_far: usize) -> Strategy;
```

and this function would be optional. It would be used to take a decision (`Proceed` to go on as usual, `RejectPath` to forget about the current node in this configuration, `GiveUp` to give up the search completely and declare it a failure). Such a function would be optional of course, passing `None` would still get the regular astar; that is what would be done under the name `astar` to keep the compatibility with previous releases.

Note that it would not be needed to implement it for `Dijkstra`; if someone needs it there they can simply use A* with a heuristic returning 0, algorithms are then equivalent.

Also, since we could guarantee that `strategy` is called right before `successors`, one could use this to pass data from `strategy` to `successors` if they need it.

What I am afraid of is that at some point someone will want to get the full path so far also, in which case this would lead to a performance hit in the general case or force us to reveal internal data structures which will complicate further internal evolutions and optimizations. This is where I am not sure this is worth extending a common algorithm instead of adapting it for a special case.

I'd consider patches if they are well thought, do not break compatibility and do not degrade performances in the general case (no strategy).

**Comment by lunikon** [comment]
Thanks a lot for your feedback! I like the `Strategy` approach but I am still a bit worried it might be too narrow. The `successors` function  is the natural place to make any decisions on how to continue the search and the more information is available there without giving away internals or moving too far away from "pure A*", the better. I'll think about it a bit and experiment with different approaches that maintain the current API of the `astar` method.
